#+title: Idea
Идеи насчёт скрипта.
Сначала предыстория. Я начал создавать скрипт в июле, я решил его сздавать потому что, я тогда любил переустанавливать арч, но всегда приходится вручную устанваливать, я видел ютуб у чела bugswriter он создал скрипт под себя, я решил спиздить его и настраивал под себя, конечно там косяков предостаточно, но я здесь чтобы исправить эти косяки и начинать использовать этот скрипт.
* Что я вообще хочу заметить:
- Я буду использовать двм, который щас у меня на комп, и бар ubar.
- Использовать rofi вместо dmenu
- У меня скрипт пиздец раздут, надо сократить и выбрать нужное. Например убрать выбор xfce, вместо него будет dwm. Есть интересная хуйня, в 3 части когда уже буду начинать добавлять конфиги двм и xinitrc. Двм можно склонировать с гит, но так не пройдёт с xinitrc. Я буду впихнуть xinitrc в everythingConfig репозиторий и с помощью wget -P <directory> www... я буду указывать куда именно сохранять файл. Также можно использовать флаг -O для сохранения под нужным именем. Всё это скомбинировать
- Там есть не нужная генерация с pywal(wal -i)


Короче, просто арч линукс с двм и некоторым нужным мне пакетом, также можно добавить doom emacs. Но лучше отдельно от арч линукса, мало ли какой то пиздец произойдёт.
